export const TRIP_INITIAL_STATE: CreateTripV2 = {
  contributorId: "",
  name: "",
  duration: 0,
  cost: 0,
  gpsVerified: 0,
  modVerified: 0,
  upvotes: 0,
  downvotes: 0,
  startLocation: "",
  startCoords: [0, 0],
  endLocation: "",
  endCoords: [0, 0],
};

export const SEGMENT_INITIAL_STATE: CreateSegmentV2 = {
  contributorId: "",
  segmentName: "",
  segmentMode: "Walk",
  landmark: "",
  instruction: "",
  gpsVerified: 0,
  modVerified: 0,
  duration: 0,
  cost: 0,
  liveStatus: [],
  waypoints: [],
  navigationSteps: [],
  startLocation: "",
  startCoords: [0, 0],
  endLocation: "",
  endCoords: [0, 0],
};
