name: Expo Jest Tests

on: 
  push:
    branches:
      - main
      - ayen/tests
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: cd app && npm install

      - name: Run Jest tests
        run: cd app && npm test